routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// localization & switch language route
Route::get('locale/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'ar'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    App::setLocale($locale);
    return redirect()->back();
})->name('lang');

//Register & Login & Logout
Auth::routes();

// Route::get('/home', 'HomeController@base')->name('home');
Route::get('/reports','HomeController@index')->name('reports');


// public routes
//Primary Page
Route::get('/', 'HomeController@base')->name('base');
//About page
Route::view('/about', 'about.index')->name('about');

// -------------------------------------------------------------------------------------------------------

//Search Routes

Route::get('search/jobs', 'SearchController@jobs')->name('search.jobs'); //allJobs
Route::post('search/getjobs', 'SearchController@getJobs')->name('search.getJobs'); //search Jobs

Route::get('search/charities', 'SearchController@charities')->name('search.charities');
Route::post('search/charities', 'SearchController@getCharities')->name('search.getCharities'); //search Charities

Route::get('search/projects', 'SearchController@projects')->name('search.projects');
Route::post('search/projects', 'SearchController@getProjects')->name('search.getProjects'); //search Projects

Route::get('search/shortages', 'SearchController@shortages')->name('search.shortages');
Route::post('search/shortages', 'SearchController@getShortages')->name('search.getShortages'); //search Shortages

Route::get('search/surpluses', 'SearchController@surpluses')->name('search.surpluses');
Route::post('search/surpluses', 'SearchController@getSurpluses')->name('search.getSurpluses'); //search Surpluses

// Route::get('search/activities', 'SearchController@activities')->name('search.activities');
// Route::post('search/{activity}/activities', 'SearchController@getActivities')->name('search.getActivities'); //search Activities

// -------------------------------------------------------------------------------------------------------

// show Routes

//project show

Route::get('projects/{project}/show', 'ProjectController@show')->name('projects.show');
// Route::get('charities/{project}/requirments', 'ProjectRequirementController@show')->name('projReqs.show');

// -------------------------------------------------------------------------------------------------------

//Charity Show
Route::get('charities/{charity}/show', 'CharityController@show')->name('charities.show');
Route::get('charities/{charity}/projects', 'CharityController@projects')->name('charities.projects');
Route::get('charities/{charity}/shortages', 'CharityController@shortages')->name('charities.shortage');
Route::get('charities/{charity}/surpluses', 'CharityController@surpluses')->name('charities.surplus');
Route::get('charities/{charity}/jobs', 'CharityController@jobs')->name('charities.jobs');

// -------------------------------------------------------------------------------------------------------
Route::get('jobs/{job}/show', 'CharityJobController@show')->name('jobs.show');
// -------------------------------------------------------------------------------------------------------

// Auth pages
Route::middleware(['auth'])->group(function () {

    //item resource
    Route::resource('items', 'ItemController')->except(['show', 'create', 'edit']);

    //charity resource
    Route::resource('charities', 'CharityController')->except(['show']);

    //project resource
    Route::resource('projects', 'ProjectController')->except(['show']);
    Route::match(['put', 'post'], 'projects/{project}/close', 'ProjectController@close')->name('projects.close');

    //Project Requirment Routes
    Route::get('project/{project}/requirments', 'ProjectRequirementController@index')->name('projReqs.index');
    Route::get('project/{project}/requirments/create', 'ProjectRequirementController@create')->name('projReqs.create');

    Route::post('project/{project}/requirments', 'ProjectRequirementController@store')->name('projReqs.store');
    Route::get('project/requirments/{projReq}/edit', 'ProjectRequirementController@edit')->name('projReqs.edit');
    Route::match(['put', 'post'], 'project/requirments/{projReq}', 'ProjectRequirementController@update')->name('projReqs.update');
    Route::delete('project/requirments/{projReq}', 'ProjectRequirementController@destroy')->name('projReqs.destroy');
    Route::match(['put', 'post'], 'projReq/{projReq}/close', 'ProjectRequirementController@close')->name('projReqs.close');

    // //fill Project Requirment
    // Route::get('projReq/{projReq}/fills', 'FillProjReqController@index')->name('projReqs.fills.index');
    // Route::get('projReq/{projReq}/fills/create', 'FillProjReqController@create')->name('projReqs.fills.create');
    // Route::post('projReq/{projReq}/fills', 'FillProjReqController@store')->name('projReqs.fills.store');
    // Route::get('projReq/fills/{fill}/edit', 'FillProjReqController@edit')->name('projReqs.fills.edit');
    // Route::match(['put', 'post'], 'projReq/fill/fills/{fill}', 'FillProjReqController@update')->name('projReqs.fills.update');
    // Route::delete('projReq/fills/{fill}', 'FillProjReqController@destroy')->name('projReqs.fills.destroy');
    // Route::match(['put', 'post'], 'projReq/fills/{fill}/close', 'FillProjReqController@close')->name('projReqs.fills.close');

    //shortage resource
    Route::resource('shortages', 'ShortageController')->except('index', 'create');
    Route::get('shortages/type/{type}/index', 'ShortageController@index')->name('shortages.index');
    Route::get('shortages/type/{type}/create', 'ShortageController@create')->name('shortages.create');

    Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');

    //fill Shortage
    Route::get('shortage/{shortage?}/fills', 'FillController@index')->name('fills.index');
    Route::get('shortage/{shortage}/fills/create/', 'FillController@create')->name('fills.create');
    Route::post('shortage/{shortage}/fills', 'FillController@store')->name('fills.store');
    Route::get('shortage/fills/{fill}/edit', 'FillController@edit')->name('fills.edit');
    Route::match(['put', 'post'], 'shortage/fill/fills/{fill}', 'FillController@update')->name('fills.update');
    Route::delete('shortage/fills/{fill}', 'FillController@destroy')->name('fills.destroy');
    Route::match(['put', 'post'], 'shortage/fills/{fill}/close', 'FillController@close')->name('fills.close');



    //volunteer resource
    Route::resource('volunteers', 'VolunteerController');

    //jobs resource
    Route::resource('jobs', 'CharityJobController')->except(['show']);
    Route::match(['put', 'post'], 'jobs/{job}/close', 'CharityJobController@close')->name('jobs.close');

    //Job request Routes
    Route::get('jobreq/{job}/request', 'VolunteerRequestController@index')->name('jobReqs.index');
    Route::get('jobreq/{job}/request/create', 'VolunteerRequestController@create')->name('jobReqs.create');
    Route::post('jobreq/{job}/request', 'VolunteerRequestController@store')->name('jobReqs.store');
    Route::get('jobreq/request/{jobReq}/edit', 'VolunteerRequestController@edit')->name('jobReqs.edit');
    Route::match(['put', 'post'], 'jobreq/request/{jobReq}', 'VolunteerRequestController@update')->name('jobReqs.update');
    Route::delete('jobreq/request/{jobReq}', 'VolunteerRequestController@destroy')->name('jobReqs.destroy');

//benifactors && charity
    Route::get('user/fills', 'FillController@MyFills')->name('user.myFills');
    Route::get('user/jobReqs', 'VolunteerRequestController@myJobRequests')->name('user.jobReqs');
// Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');
    // Route::resource('benfes', 'BenefactorController');


    //messages
Route::get('messages/index/{type}', 'MessageController@index')->name('messages.index');

// Route::get('fill/{fill}/messages', 'MessageController@index')->name('messages.fill.index');
Route::post('fill/{fill}/messages/type/{type}', 'MessageController@send')->name('messages.send');
Route::get('fill/{fill}/messages/type/{type}','MessageController@show')->name('fill.messages');
});

app/Models/Volunteer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Volunteer extends Model
{
    //
     protected $guarded = [];
        public $incrementing = false;
        protected $primaryKey = 'user_id';
     /**
      * Get the user that owns the Volunteer
      *
      * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
      */
     public function user()
     {
         return $this->belongsTo('App\Models\User', 'user_id');
     }

     /**
      * Get all of the jobRequests for the Volunteer
      *
      * @return \Illuminate\Database\Eloquent\Relations\HasMany
      */
     public function jobRequests()
     {
         return $this->hasMany('App\Models\VolunteerRequest', 'volunteer_id','user_id');
     }
}

app/Http/Controllers/VolunteerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Volunteer;
use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class VolunteerController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('can:admin')->only('destroy','index');
        // $this->middleware('can:v_access,volunteer')->only(['edit','update']);
        // $this->middleware('can:volunteer')->except('index','destroy','show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $volunteers = Volunteer::all();
        return view('volunteers.index', ['volunteers' => $volunteers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        if (Auth::user()->volunteer != null) {
            return redirect(route('volunteers.edit', Auth::user()->volunteer));
        }
        return view('volunteers.crup');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->except(['profile']); // ما بخزن الصور متل ما هنن
        if (request()->hasfile('profile')) {
            $profilefilepath = public_path(config('path.vprofile'));
            $profilefile = request()->file('profile'); //بتعطي الصورة كفايل
            $profilename = time() . "_." . $request->profile->extension();
            $profilefile->move($profilefilepath, $profilename);
            $input = array_merge($input, ["profile" => $profilename]);
        }

        $input = array_merge($input, ["user_id" => Auth::user()->id]);
        $volunteer = Volunteer::create($input);
            return redirect(route('volunteers.show', $volunteer));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function show(Volunteer $volunteer)
    {
        //
        return view('volunteers.show', compact('volunteer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function edit(Volunteer $volunteer)
    {
        return view('volunteers.crup', compact('volunteer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Volunteer $volunteer)
    {
        //
        $input = $request->except(['profile']);
        if (request()->hasfile('profile')) {
            $profilefilepath = public_path(config('path.vprofile'));
            if ($volunteer->profile != null) {
                if (Storage::exists($profilefilepath . $volunteer->profile)) {
                    File::delete($profilefilepath . $volunteer->profile);
                }
            }

            $profilefile = request()->file('profile');
            $profilename = time() . "_." . $request->profile->extension();
            $profilefile->move($profilefilepath, $profilename);
            $input = array_merge($input, ["profile" => $profilename]);
        }



        $volunteer->update($input);
        if ($volunteer->user_id == Auth::user()->id) {

            return redirect(route('volunteers.show', $volunteer));
        } else {
            return redirect(route('volunteers.index'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Volunteer  $volunteer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Volunteer $volunteer)
    {
        //
        $volunteer->delete();
        return redirect(route('volunteers.index'));
    }


}

resources/views/volunteers/crup.blade.php
@extends('layouts.app')
@section('content')

    <div class="row justify-content-center">
        <div class="col-md">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form
                        action="{{ empty($volunteer) ? route('volunteers.store') : route('volunteers.update', $volunteer) }}"
                        method="Post" enctype="multipart/form-data">
                        @csrf
                        @if (!empty($volunteer))
                            @method('PUT')
                        @endif

                        <!--profile-->
                        <div class="row">
                            <div class="col-md-2 col-form-label  ">
                                {{-- style="text-align:start"> --}}
                                <label for="profile">{{ __('Profile_pic') }}:</label>
                            </div>
                            @if (!empty($volunteer))
                                <div class="col-md-2 col-form-label " style="text-align:start">
                                    <img src="{{ asset(config('path.vprofile') . $volunteer->profile) }}"
                                        class="img-fluid img-thumbnail">
                                </div>
                            @endif
                            <div class="@if (!empty($volunteer)) col-8 @else col-md-10 @endif">
                                <input class="form-control" type="file" name="profile" @if (empty($volunteer)) required @endif>
                            </div>
                        </div>

                        <!--name-->
                        <div class="row">
                            <div class="col-md-2 col-form-label  ">
                                <label for="name_ar">{{ __('Arabic Name') }}:</label>
                            </div>
                            <div class="col-md-4"><input class="form-control" type="text" name="name_ar" value=@if (!empty($volunteer)) "{{ $volunteer->name_ar }}"@else "{{ old('name_ar') }}" @endif>
                            </div>
                            <div class="col-md-2 col-form-label  ">
                                <label for="name_en">{{ __('English Name') }}:</label>
                            </div>
                            <div class="col-md-4"><input class="form-control" type="text" name="name_en" value=@if (!empty($volunteer)) "{{ $volunteer->name_en }}" @else "{{ old('name_en') }}" @endif>
                            </div>
                        </div>

                        <!--Birthday-->
                        <div class="row">
                            <div class="col-md-2 col-form-label  ">
                                <label for="birth_date">{{ __('Birthday') }}:</label>
                            </div>
                            <div class="col-md-4"><input class="form-control" type="date" name="birth_date" value=@if (!empty($volunteer)) "{{ $volunteer->birth_date }}"@else "{{ old('birth_date') }}" @endif>
                            </div>
                            <!--email-->
                            <div class="col-md-2 col-form-label  ">
                                <label for="email">{{ __('Email') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <input class="form-control" type="email" value=@if (!empty($volunteer)) "{{ $volunteer->user->email }}" @else "{{ old('email') }}" @endif disabled>
                            </div>
                        </div>
                        <hr>
                        <!--education-->
                        <div class="row">
                            <div class="col-md-2 col-form-label  ">
                                <label for="education_ar">{{ __('Arabic Education') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <textarea class="form-control"
                                    name="education_ar">@if (!empty($volunteer)){{ $volunteer->education_ar }}@else {{ old('education_ar') }}@endif</textarea>
                            </div>
                            <div class="col-md-2 col-form-label  ">
                                <label for="education_en">{{ __('English Education') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <textarea class="form-control"
                                    name="education_en">@if (!empty($volunteer)){{ $volunteer->education_en }}@else{{ old('education_en') }} @endif</textarea>
                            </div>
                        </div>
                        <br>
                        <!--Skills-->
                        <div class="row">
                            <div class="col-md-2 col-form-label  ">
                                <label for="skills_ar">{{ __('Arabic Skills') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <textarea class="form-control"
                                    name="skills_ar">@if (!empty($volunteer)){{ $volunteer->skills_ar }}@else{{ old('skills_ar') }} @endif</textarea>
                            </div>
                            <div class="col-md-2 col-form-label  ">
                                <label for="skills_en">{{ __('English Skills') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <textarea class="form-control"
                                    name="skills_en">@if (!empty($volunteer)){{ $volunteer->skills_en }}@else{{ old('skills_en') }}@endif</textarea>
                            </div>
                        </div>
                        <br>
                        <!--Experiences-->
                        <div class="row">
                            <div class="col-md-2 col-form-label  ">
                                <label for="experiences_ar">{{ __('Arabic Experiences') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <textarea class="form-control"
                                    name="experiences_ar">@if (!empty($volunteer)){{ $volunteer->experiences_ar }}@else{{ old('experiences_ar') }}@endif</textarea>
                            </div>
                            <div class="col-md-2 col-form-label  ">
                                <label for="experiences_en">{{ __('English Experiences') }}:</label>
                            </div>
                            <div class="col-md-4">
                                <textarea class="form-control"
                                    name="experiences_en">@if (!empty($volunteer)){{ $volunteer->experiences_en }}@else{{ old('experiences_en') }}@endif</textarea>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-6 text-md-center">
                                <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                            </div>
                            <div class="col-6 text-md-center">
                                {{-- @can('admin')
                            <a href="{{ route('volunteers.index') }}" type="button"
                                class="btn btn-secondary">{{ __('Cancel') }}</a>
                            @else
                            <a href="{{ route('base') }}" type="button"
                                class="btn btn-secondary">{{ __('Cancel') }}</a>
                            @endcan --}}
                                <a href="#" class="btn btn-secondary"
                                    onclick="location.href = document.referrer; return false;">{{ __('Cancel') }}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/volunteers/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">{{ __('id') }}</th>
                                    <th scope="col">{{ __('Name') }}</th>
                                    <th scope="col">{{ __('Profile_pic') }}</th>
                                    <th scope="col">{{ __('Birthday') }}</th>
                                    <th scope="col">{{ __('Email') }}</th>
                                    <th scope="col">{{ __('Education') }}</th>
                                    <th scope="col">{{ __('Skills') }}</th>
                                    <th scope="col">{{ __('Experiences') }}</th>
                                    <th scope="col" width="150">{{ __('Control') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($volunteers as $volunteer)
                                    <tr>
                                        <th scope="row">
                                            {{ $volunteer->user_id }}
                                        </th>

                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $volunteer->name_ar }}
                                            @else
                                                {{ $volunteer->name_en }}
                                            @endif
                                        </td>

                                        <td style="width:10% ; max-width:15%;">

                                            <img src="{{ asset(config('path.vprofile') . $volunteer->profile) }}"
                                                class=" img-fluid img-thumbnail">
                                        </td>


                                        <td>{{ $volunteer->birth_date }}</td>
                                        <td>{{ $volunteer->user->email }}</td>

                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $volunteer->education_ar }}
                                            @else
                                                {{ $volunteer->education_en }}
                                            @endif
                                        </td>

                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $volunteer->skills_ar }}
                                            @else
                                                {{ $volunteer->skills_en }}
                                            @endif
                                        </td>

                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $volunteer->experiences_ar }}
                                            @else
                                                {{ $volunteer->experiences_en }}
                                            @endif
                                        </td>


                                        <td>
                                            <div class="btn-group-justified">
                                                <div class="btn-group">
                                                    <a class="btn btn-outline-primary rounded-circle"
                                                        href="{{ route('volunteers.show', $volunteer) }}">
                                                        <i class="zmdi zmdi-eye"></i>
                                                    </a>
                                                </div>
                                                <div class="btn-group">
                                                    <a class="btn btn-outline-warning rounded-circle"
                                                        href="{{ route('volunteers.edit', $volunteer->user_id) }}">
                                                        <i class="zmdi zmdi-edit"></i>
                                                    </a>
                                                </div>
                                                <div class="btn-group">
                                                    <form action="{{ route('volunteers.destroy', $volunteer->user_id) }}"
                                                        method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button Type="submit" class="btn rounded-circle btn-outline-danger">
                                                            <i class="zmdi zmdi-delete"></i>
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection