routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// localization & switch language route
Route::get('locale/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'ar'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    App::setLocale($locale);
    return redirect()->back();
})->name('lang');

//Register & Login & Logout
Auth::routes();

// Route::get('/home', 'HomeController@base')->name('home');
Route::get('/reports','HomeController@index')->name('reports');


// public routes
//Primary Page
Route::get('/', 'HomeController@base')->name('base');
//About page
Route::view('/about', 'about.index')->name('about');

// -------------------------------------------------------------------------------------------------------

//Search Routes

Route::get('search/jobs', 'SearchController@jobs')->name('search.jobs'); //allJobs
Route::post('search/getjobs', 'SearchController@getJobs')->name('search.getJobs'); //search Jobs

Route::get('search/charities', 'SearchController@charities')->name('search.charities');
Route::post('search/charities', 'SearchController@getCharities')->name('search.getCharities'); //search Charities

Route::get('search/projects', 'SearchController@projects')->name('search.projects');
Route::post('search/projects', 'SearchController@getProjects')->name('search.getProjects'); //search Projects

Route::get('search/shortages', 'SearchController@shortages')->name('search.shortages');
Route::post('search/shortages', 'SearchController@getShortages')->name('search.getShortages'); //search Shortages

Route::get('search/surpluses', 'SearchController@surpluses')->name('search.surpluses');
Route::post('search/surpluses', 'SearchController@getSurpluses')->name('search.getSurpluses'); //search Surpluses

// Route::get('search/activities', 'SearchController@activities')->name('search.activities');
// Route::post('search/{activity}/activities', 'SearchController@getActivities')->name('search.getActivities'); //search Activities

// -------------------------------------------------------------------------------------------------------

// show Routes

//project show

Route::get('projects/{project}/show', 'ProjectController@show')->name('projects.show');
// Route::get('charities/{project}/requirments', 'ProjectRequirementController@show')->name('projReqs.show');

// -------------------------------------------------------------------------------------------------------

//Charity Show
Route::get('charities/{charity}/show', 'CharityController@show')->name('charities.show');
Route::get('charities/{charity}/projects', 'CharityController@projects')->name('charities.projects');
Route::get('charities/{charity}/shortages', 'CharityController@shortages')->name('charities.shortage');
Route::get('charities/{charity}/surpluses', 'CharityController@surpluses')->name('charities.surplus');
Route::get('charities/{charity}/jobs', 'CharityController@jobs')->name('charities.jobs');

// -------------------------------------------------------------------------------------------------------
Route::get('jobs/{job}/show', 'CharityJobController@show')->name('jobs.show');
// -------------------------------------------------------------------------------------------------------

// Auth pages
Route::middleware(['auth'])->group(function () {

    //item resource
    Route::resource('items', 'ItemController')->except(['show', 'create', 'edit']);

    //charity resource
    Route::resource('charities', 'CharityController')->except(['show']);

    //project resource
    Route::resource('projects', 'ProjectController')->except(['show']);
    Route::match(['put', 'post'], 'projects/{project}/close', 'ProjectController@close')->name('projects.close');

    //Project Requirment Routes
    Route::get('project/{project}/requirments', 'ProjectRequirementController@index')->name('projReqs.index');
    Route::get('project/{project}/requirments/create', 'ProjectRequirementController@create')->name('projReqs.create');

    Route::post('project/{project}/requirments', 'ProjectRequirementController@store')->name('projReqs.store');
    Route::get('project/requirments/{projReq}/edit', 'ProjectRequirementController@edit')->name('projReqs.edit');
    Route::match(['put', 'post'], 'project/requirments/{projReq}', 'ProjectRequirementController@update')->name('projReqs.update');
    Route::delete('project/requirments/{projReq}', 'ProjectRequirementController@destroy')->name('projReqs.destroy');
    Route::match(['put', 'post'], 'projReq/{projReq}/close', 'ProjectRequirementController@close')->name('projReqs.close');

    // //fill Project Requirment
    // Route::get('projReq/{projReq}/fills', 'FillProjReqController@index')->name('projReqs.fills.index');
    // Route::get('projReq/{projReq}/fills/create', 'FillProjReqController@create')->name('projReqs.fills.create');
    // Route::post('projReq/{projReq}/fills', 'FillProjReqController@store')->name('projReqs.fills.store');
    // Route::get('projReq/fills/{fill}/edit', 'FillProjReqController@edit')->name('projReqs.fills.edit');
    // Route::match(['put', 'post'], 'projReq/fill/fills/{fill}', 'FillProjReqController@update')->name('projReqs.fills.update');
    // Route::delete('projReq/fills/{fill}', 'FillProjReqController@destroy')->name('projReqs.fills.destroy');
    // Route::match(['put', 'post'], 'projReq/fills/{fill}/close', 'FillProjReqController@close')->name('projReqs.fills.close');

    //shortage resource
    Route::resource('shortages', 'ShortageController')->except('index', 'create');
    Route::get('shortages/type/{type}/index', 'ShortageController@index')->name('shortages.index');
    Route::get('shortages/type/{type}/create', 'ShortageController@create')->name('shortages.create');

    Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');

    //fill Shortage
    Route::get('shortage/{shortage?}/fills', 'FillController@index')->name('fills.index');
    Route::get('shortage/{shortage}/fills/create/', 'FillController@create')->name('fills.create');
    Route::post('shortage/{shortage}/fills', 'FillController@store')->name('fills.store');
    Route::get('shortage/fills/{fill}/edit', 'FillController@edit')->name('fills.edit');
    Route::match(['put', 'post'], 'shortage/fill/fills/{fill}', 'FillController@update')->name('fills.update');
    Route::delete('shortage/fills/{fill}', 'FillController@destroy')->name('fills.destroy');
    Route::match(['put', 'post'], 'shortage/fills/{fill}/close', 'FillController@close')->name('fills.close');



    //volunteer resource
    Route::resource('volunteers', 'VolunteerController');

    //jobs resource
    Route::resource('jobs', 'CharityJobController')->except(['show']);
    Route::match(['put', 'post'], 'jobs/{job}/close', 'CharityJobController@close')->name('jobs.close');

    //Job request Routes
    Route::get('jobreq/{job}/request', 'VolunteerRequestController@index')->name('jobReqs.index');
    Route::get('jobreq/{job}/request/create', 'VolunteerRequestController@create')->name('jobReqs.create');
    Route::post('jobreq/{job}/request', 'VolunteerRequestController@store')->name('jobReqs.store');
    Route::get('jobreq/request/{jobReq}/edit', 'VolunteerRequestController@edit')->name('jobReqs.edit');
    Route::match(['put', 'post'], 'jobreq/request/{jobReq}', 'VolunteerRequestController@update')->name('jobReqs.update');
    Route::delete('jobreq/request/{jobReq}', 'VolunteerRequestController@destroy')->name('jobReqs.destroy');

//benifactors && charity
    Route::get('user/fills', 'FillController@MyFills')->name('user.myFills');
    Route::get('user/jobReqs', 'VolunteerRequestController@myJobRequests')->name('user.jobReqs');
// Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');
    // Route::resource('benfes', 'BenefactorController');


    //messages
Route::get('messages/index/{type}', 'MessageController@index')->name('messages.index');

// Route::get('fill/{fill}/messages', 'MessageController@index')->name('messages.fill.index');
Route::post('fill/{fill}/messages/type/{type}', 'MessageController@send')->name('messages.send');
Route::get('fill/{fill}/messages/type/{type}','MessageController@show')->name('fill.messages');
});

resources/views/jobs/crup.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ __('Job Information') }}</h5>
                </div>
                <div class="card-body">
                    <form action="{{ empty($job) ? route('jobs.store') : route('jobs.update', $job) }}" method="Post"
                        enctype="multipart/form-data">
                        @csrf
                        @if (!empty($job))
                            @method('PUT')
                        @endif

                        <!--name-->
                        <div class="row">
                            <div class="col">
                                <div class="row">
                                    <div class="col-md-4 col-form-label">
                                        <label for="job_title_ar">{{ __('Title AR') }}:</label>
                                    </div>
                                    <div class="col-8">
                                    <input class="form-control" type="text" name="job_title_ar" required @if (!empty($job)) value="{{ $job->job_title_ar }}" @else
                                            value="{{ old('job_title_ar') }}" @endif>
                                    </div>
                                    <div class="col-md-4 col-form-label">
                                        <label for="job_details_ar">{{ __('Job details AR') }}:</label>
                                    </div>
                                    <div class="col-8">
                                        <textarea class="form-control my-1" type="text" required
                                            name="job_details_ar">@if (!empty($job)){{ $job->job_details_ar }} @else{{ old('job_details_ar') }} @endif</textarea>
                                    </div>
                                    <div class="col-md-4 col-form-label">
                                        <label for="location_ar">{{ __('Location AR') }}:</label>
                                    </div>
                                    <div class="col-8">
                                        <textarea class="form-control my-1" type="text"
                                            name="location_ar">@if (!empty($job)){{ $job->location_ar }} @else{{ old('location_ar') }} @endif</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="row">
                                    <div class="col-md-4 col-form-label">
                                        <label for="job_title_en">{{ __('Title EN') }}:</label>
                                    </div>
                                <div class="col-8"><input class="form-control" type="text" name="job_title_en" @if (!empty($job)) value="{{ $job->job_title_en }}" @else
                                            value="{{ old('job_title_en') }}" @endif required>
                                    </div>

                                    <div class="col-md-4 col-form-label">
                                        <label for="job_details_en">{{ __('Job details EN') }}:</label>
                                    </div>
                                    <div class="col-8">
                                        <textarea class="form-control my-1" type="text" required
                                            name="job_details_en">@if (!empty($job)){{ $job->job_details_en }} @else{{ old('job_details_en') }} @endif</textarea>
                                    </div>
                                    <div class="col-md-4 col-form-label">
                                        <label for="location_en">{{ __('Location EN') }}:</label>
                                    </div>
                                    <div class="col-8">
                                        <textarea class="form-control my-1" type="text"
                                            name="location_en">@if (!empty($job)){{ $job->location_en }} @else{{ old('location_en') }} @endif</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="state">{{ __('State') }}</label>
                                    <select id="state" class="custom-select" name="state" required>
                                        @if (!empty($job))
                                            <option value="{{ $job->state }}" selected>{{ __($job->state) }}</option>
                                        @endif
                                        <option value="waiting">{{ __('Waiting') }}</option>
                                        <option value="undeployed">{{ __('undeployed') }}</option>
                                        <option value="closed">{{ __('Closed') }}</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="tag">{{ __('Tags') }}</label>
                                    <input type="text" class="form-control" name="tag" id="tag" @if (!empty($job)) value="{{ $job->tag }}" @else value="{{ old('tag') }}" @endif>
                                </div>
                            </div>
                            <div class="col d-flex align-items-end d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ __('Manage Jobs') }}
                        <a id="top-plus" href="{{ route('jobs.create') }}" class="btn btn-outline-success  float-left">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">{{ __('id') }}</th>
                                    <th scope="col">{{ __('Title') }}</th>
                                    <th scope="col">{{ __('Details') }}</th>
                                    <th scope="col">{{ __('Created at') }}</th>
                                    <th scope="col">{{ __('Location') }}</th>
                                    <th scope="col">{{ __('Tags') }}</th>
                                    <th scope="col">{{ __('State') }}</th>

                                    <th scope="col" width="150">{{ __('Control') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($jobs as $job)
                                    <tr>
                                        <th scope="row">{{ $job->id }}</th>
                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $job->job_title_ar }}
                                            @else
                                                {{ $job->job_title_en }}
                                            @endif
                                        </td>
                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $job->job_details_ar }}
                                            @else
                                                {{ $job->job_details_en }}
                                            @endif
                                        </td>
                                        <td>{{ $job->created_at }}</td>
                                        <td>
                                            @if (config('app.locale') == 'ar')
                                                {{ $job->location_ar }}
                                            @else
                                                {{ $job->location_en }}
                                            @endif

                                        </td>
                                        <td>{{ $job->tag }}</td>
                                        <td>{{ __($job->state) }}
                                            @if ($job->state != 'closed')
                                                <form action="{{ route('jobs.close', $job->id) }}" method="POST">
                                                    @csrf
                                                    @method('put')
                                                    <button Type="submit" class="btn btn-outline-danger">
                                                        {{ __('Close') }}
                                                    </button>
                                                </form>
                                            @endif
                                        </td>
                                        <td>
                                            <div class="btn-group-justified">
                                                <div class="btn-group">
                                                    <a class="btn btn-outline-warning rounded-circle"
                                                        href="{{ route('jobs.edit', $job->id) }}">
                                                        <i class="zmdi zmdi-edit"></i>
                                                    </a>
                                                </div>
                                                <div class="btn-group">
                                                    <form action="{{ route('jobs.destroy', $job->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button Type="submit" class="btn rounded-circle btn-outline-danger">
                                                            <i class="zmdi zmdi-delete"></i>
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="btn-group-justified">
                                                <div class="btn-group">
                                                    <a class="btn btn-outline-info" href="{{ route('jobReqs.index', $job) }}">
                                                       {{__('Job Requests')}}
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-9 col-md-8 right-wrapper">
            <div class="card mb-2 shadow">
                <div class="card-body">
                    {{-- <div class="col-md-12 grid-margin"> --}}
                    <div class="card rounded">
                        <!-- card-header -->
                        <div class="card-header">
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="d-flex align-items-center">
                                    <div class="ml-2">
                                        <span>
                                            <h4>
                                                @if (config('app.locale') == 'ar')
                                                    {{ $job->job_title_ar }}
                                                @else
                                                    {{ $job->job_title_en }}
                                                @endif
                                            </h4>
                                        </span>
                                    </div>
                                </div>
                                <ul class="d-sm-flex my-0">
                                    {{ __('Date of publication') }}: {{ $job->created_at }}
                                </ul>
                            </div>
                        </div>

                        <!-- card-body -->
                        <!-- text with image -->
                        <div class="card-body">
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="d-flex align-items-center">
                                    <div class="ml-2">
                                        <span>
                                            <h6 class="mb-3 tx-14">
                                                {{ __('Belonging to') }} :
                                                <a href="{{ route('charities.show', $job->charity) }}">
                                                    @if (config('app.locale') == 'ar')
                                                        {{ $job->charity->name_ar }}
                                                    @else
                                                        {{ $job->charity->name_en }}
                                                    @endif
                                                </a>
                                            </h6>
                                        </span>
                                    </div>
                                </div>
                                <ul class="d-sm-flex my-0">
                                    <div class="card-body">
                                        <h5>{{ __('State') }} : {{ __($job->state) }}</h5>
                                    </div>
                                </ul>
                            </div>
                            <p>
                                @if (config('app.locale') == 'ar')
                                    {{ $job->job_details_ar }}
                                @else
                                    {{ $job->job_details_en }}
                                @endif
                            </p>
                            <div>
                                <p>
                                    @if (config('app.locale') == 'ar')
                                        {{ $job->location_ar }}
                                    @else
                                        {{ $job->location_en }}
                                    @endif
                                </p>
                            </div>
                            <form action="{{ route('jobReqs.store', $job) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                <label>{{ __('Upload CV') }} : </label>
                                <input type="file" name="cv" class="form-control" required>
                                <br>
                                <button class="btn btn-primary @if (config('app.locale')=='ar' ) float-left @else float-right @endif">{{ __('Submit') }}</button>
                            </form>
                        </div>
                    </div>
                    {{-- </div> --}}
                </div>
            </div>
        </div>

        {{-- Newest Jobs --}}
        <div class="col-lg-3 col-md-4 order-6 order-lg-12 order-md-6 order-sm-6 mb-1">
            <div class="card mb-2 shadow ">
                <div class="card-body ">
                    <h5 class="card-title">{{ __('Newest Jobs') }}
                    </h5>
                    <hr class="mb-0">
                    <div class="list-group list-group-flush">
                        @foreach ($jobs as $job)
                            <a class="list-group-item list-group-item-action" href="{{ route('jobs.show', $job) }}">
                                <h6 class="font-weight-bold">
                                    @if (app()->getLocale() == 'ar')
                                    {{ $job->job_title_ar }} @else {{ $job->job_title_en }}
                                    @endif
                                </h6>
                                <p class="card-text text-truncate">
                                    @if (app()->getLocale() == 'ar')
                                        {{ $job->job_details_ar }}
                                    @else {{ $job->job_details_en }}@endif
                                </p>
                            </a>
                        @endforeach
                    </div>
                    @if (app()->getLocale() == 'ar')
                        <a class="@if (app()->getLocale() == 'ar') float-left
                        @else
                            float-right @endif" href="{{ route('search.jobs') }}">{{ __('View more') }}
                            <i class="fa fa-arrow-circle-left"></i></a>
                    @else
                        <a class="float-right" href="{{ route('search.jobs') }}">{{ __('View more') }}
                            <i class="fa fa-arrow-circle-right"></i></a>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection