routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// localization & switch language route
Route::get('locale/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'ar'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    App::setLocale($locale);
    return redirect()->back();
})->name('lang');

//Register & Login & Logout
Auth::routes();

// Route::get('/home', 'HomeController@base')->name('home');
Route::get('/reports','HomeController@index')->name('reports');


// public routes
//Primary Page
Route::get('/', 'HomeController@base')->name('base');
//About page
Route::view('/about', 'about.index')->name('about');

// -------------------------------------------------------------------------------------------------------

//Search Routes

Route::get('search/jobs', 'SearchController@jobs')->name('search.jobs'); //allJobs
Route::post('search/getjobs', 'SearchController@getJobs')->name('search.getJobs'); //search Jobs

Route::get('search/charities', 'SearchController@charities')->name('search.charities');
Route::post('search/charities', 'SearchController@getCharities')->name('search.getCharities'); //search Charities

Route::get('search/projects', 'SearchController@projects')->name('search.projects');
Route::post('search/projects', 'SearchController@getProjects')->name('search.getProjects'); //search Projects

Route::get('search/shortages', 'SearchController@shortages')->name('search.shortages');
Route::post('search/shortages', 'SearchController@getShortages')->name('search.getShortages'); //search Shortages

Route::get('search/surpluses', 'SearchController@surpluses')->name('search.surpluses');
Route::post('search/surpluses', 'SearchController@getSurpluses')->name('search.getSurpluses'); //search Surpluses

// Route::get('search/activities', 'SearchController@activities')->name('search.activities');
// Route::post('search/{activity}/activities', 'SearchController@getActivities')->name('search.getActivities'); //search Activities

// -------------------------------------------------------------------------------------------------------

// show Routes

//project show

Route::get('projects/{project}/show', 'ProjectController@show')->name('projects.show');
// Route::get('charities/{project}/requirments', 'ProjectRequirementController@show')->name('projReqs.show');

// -------------------------------------------------------------------------------------------------------

//Charity Show
Route::get('charities/{charity}/show', 'CharityController@show')->name('charities.show');
Route::get('charities/{charity}/projects', 'CharityController@projects')->name('charities.projects');
Route::get('charities/{charity}/shortages', 'CharityController@shortages')->name('charities.shortage');
Route::get('charities/{charity}/surpluses', 'CharityController@surpluses')->name('charities.surplus');
Route::get('charities/{charity}/jobs', 'CharityController@jobs')->name('charities.jobs');

// -------------------------------------------------------------------------------------------------------
Route::get('jobs/{job}/show', 'CharityJobController@show')->name('jobs.show');
// -------------------------------------------------------------------------------------------------------

// Auth pages
Route::middleware(['auth'])->group(function () {

    //item resource
    Route::resource('items', 'ItemController')->except(['show', 'create', 'edit']);

    //charity resource
    Route::resource('charities', 'CharityController')->except(['show']);

    //project resource
    Route::resource('projects', 'ProjectController')->except(['show']);
    Route::match(['put', 'post'], 'projects/{project}/close', 'ProjectController@close')->name('projects.close');

    //Project Requirment Routes
    Route::get('project/{project}/requirments', 'ProjectRequirementController@index')->name('projReqs.index');
    Route::get('project/{project}/requirments/create', 'ProjectRequirementController@create')->name('projReqs.create');

    Route::post('project/{project}/requirments', 'ProjectRequirementController@store')->name('projReqs.store');
    Route::get('project/requirments/{projReq}/edit', 'ProjectRequirementController@edit')->name('projReqs.edit');
    Route::match(['put', 'post'], 'project/requirments/{projReq}', 'ProjectRequirementController@update')->name('projReqs.update');
    Route::delete('project/requirments/{projReq}', 'ProjectRequirementController@destroy')->name('projReqs.destroy');
    Route::match(['put', 'post'], 'projReq/{projReq}/close', 'ProjectRequirementController@close')->name('projReqs.close');

    // //fill Project Requirment
    // Route::get('projReq/{projReq}/fills', 'FillProjReqController@index')->name('projReqs.fills.index');
    // Route::get('projReq/{projReq}/fills/create', 'FillProjReqController@create')->name('projReqs.fills.create');
    // Route::post('projReq/{projReq}/fills', 'FillProjReqController@store')->name('projReqs.fills.store');
    // Route::get('projReq/fills/{fill}/edit', 'FillProjReqController@edit')->name('projReqs.fills.edit');
    // Route::match(['put', 'post'], 'projReq/fill/fills/{fill}', 'FillProjReqController@update')->name('projReqs.fills.update');
    // Route::delete('projReq/fills/{fill}', 'FillProjReqController@destroy')->name('projReqs.fills.destroy');
    // Route::match(['put', 'post'], 'projReq/fills/{fill}/close', 'FillProjReqController@close')->name('projReqs.fills.close');

    //shortage resource
    Route::resource('shortages', 'ShortageController')->except('index', 'create');
    Route::get('shortages/type/{type}/index', 'ShortageController@index')->name('shortages.index');
    Route::get('shortages/type/{type}/create', 'ShortageController@create')->name('shortages.create');

    Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');

    //fill Shortage
    Route::get('shortage/{shortage?}/fills', 'FillController@index')->name('fills.index');
    Route::get('shortage/{shortage}/fills/create/', 'FillController@create')->name('fills.create');
    Route::post('shortage/{shortage}/fills', 'FillController@store')->name('fills.store');
    Route::get('shortage/fills/{fill}/edit', 'FillController@edit')->name('fills.edit');
    Route::match(['put', 'post'], 'shortage/fill/fills/{fill}', 'FillController@update')->name('fills.update');
    Route::delete('shortage/fills/{fill}', 'FillController@destroy')->name('fills.destroy');
    Route::match(['put', 'post'], 'shortage/fills/{fill}/close', 'FillController@close')->name('fills.close');



    //volunteer resource
    Route::resource('volunteers', 'VolunteerController');

    //jobs resource
    Route::resource('jobs', 'CharityJobController')->except(['show']);
    Route::match(['put', 'post'], 'jobs/{job}/close', 'CharityJobController@close')->name('jobs.close');

    //Job request Routes
    Route::get('jobreq/{job}/request', 'VolunteerRequestController@index')->name('jobReqs.index');
    Route::get('jobreq/{job}/request/create', 'VolunteerRequestController@create')->name('jobReqs.create');
    Route::post('jobreq/{job}/request', 'VolunteerRequestController@store')->name('jobReqs.store');
    Route::get('jobreq/request/{jobReq}/edit', 'VolunteerRequestController@edit')->name('jobReqs.edit');
    Route::match(['put', 'post'], 'jobreq/request/{jobReq}', 'VolunteerRequestController@update')->name('jobReqs.update');
    Route::delete('jobreq/request/{jobReq}', 'VolunteerRequestController@destroy')->name('jobReqs.destroy');

//benifactors && charity
    Route::get('user/fills', 'FillController@MyFills')->name('user.myFills');
    Route::get('user/jobReqs', 'VolunteerRequestController@myJobRequests')->name('user.jobReqs');
// Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');
    // Route::resource('benfes', 'BenefactorController');


    //messages
Route::get('messages/index/{type}', 'MessageController@index')->name('messages.index');

// Route::get('fill/{fill}/messages', 'MessageController@index')->name('messages.fill.index');
Route::post('fill/{fill}/messages/type/{type}', 'MessageController@send')->name('messages.send');
Route::get('fill/{fill}/messages/type/{type}','MessageController@show')->name('fill.messages');
});

app/Models/Shortage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Shortage extends Model
{
    //
    protected $guarded = [];

    /**
     * Get all of the fills for the Shortage
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function fills()
    {
        return $this->hasMany('App\Models\Fill', 'shortage_id');
    }

    /**
     * Get the charity that owns the Shortage
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function charity()
    {
        return $this->belongsTo('App\Models\Charity', 'charity_id', 'user_id');
    }

    /**
     * Get the item that owns the Shortage
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function item()
    {
        return $this->belongsTo('App\Models\Item', 'item_id');
    }
    public function completedQuantity()
    {
        # code...
        if ($this->state == 'closed') {
            return $this->quantity;
        }

        return $this->fills()->where('state', 'completed')->sum('quantity');

    }

    public function rest()
    {
        # code...
        return $this->quantity - $this->completedQuantity();
    }
    public function completePercent()
    {
        # code...
        if ($this->state == 'closed') {
            return 100;
        }

        $complete = $this->completedQuantity();
        $all = $this->quantity;
        if ($all != 0) {
            return $complete * 100 / $all;
        }
        return 0;
    }

    public function restPercent()
    {
        # code...
        return 100 - $this->completePercent();
    }

    /**
     * Get the project that owns the Shortage
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function project()
    {
        return $this->belongsTo(Project::class, 'project_id');
    }
}

app/Http/Controllers/ShortageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Shortage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ShortageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(string $type)
    {
        //
        if ($type == "min") {
            $shortages = Auth::user()->charity->shortages;
            return view('shortages.index', compact('shortages'));

        }
        elseif ($type == "plus") {
            $surpluses = Auth::user()->charity->surpluses;
            return view('shortages.surpIndex', compact('surpluses'));
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(string $type)
    {
        //
        $items = Item::all();
        return view('shortages.crup', compact('items','type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //TODO accsess To Charity Only
        $data = array_merge($request->all(), ['charity_id' => Auth::user()->id]);
        $shortage = Shortage::create($data);
        return redirect(route('shortages.index', $shortage->type));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Shortage  $shortage
     * @return \Illuminate\Http\Response
     */
    public function show(Shortage $shortage)
    {
        //
        return view('shortages.show', compact('shortage'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Shortage  $shortage
     * @return \Illuminate\Http\Response
     */
    public function edit(Shortage $shortage)
    {
        //
        $items = Item::all();
        return view('shortages.crup', compact('shortage', 'items'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Shortage  $shortage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Shortage $shortage)
    {
        //
        $shortage->update($request->all());
        return redirect(route('shortages.index', $shortage->type));
        // return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Shortage  $shortage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Shortage $shortage)
    {
        //
        $shortage->delete();
        return back();

    }

    public function close(Shortage $shortage)
    {
        # code...
        $shortage->state = 'closed';
        $shortage->save();
        return back();

    }
}

resources/views/shortages/crup.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ __('Item Information') }}</h5>
                </div>
                <div class="card-body">
                    <form action="{{ empty($shortage) ? route('shortages.store') : route('shortages.update', $shortage) }}"
                        method="POST" enctype="multipart/form-data">
                        @csrf
                        @if (!empty($shortage))
                            @method('PUT')
                        @endif
                        <!--name-->
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="item_id">{{ __('Item') }}</label>
                                    <select id="" class="form-control" name="item_id" required>
                                        @if (!empty($shortage))
                                            <option value="{{ $shortage->item_id }}" selected>
                                                {{ $shortage->item->name_ar }}-{{ $shortage->item->name_en }}</option>
                                        @endif
                                        @foreach ($items as $item)
                                            <option value="{{ $item->id }}">{{ $item->name_ar }}-{{ $item->name_en }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="quantity">{{ __('Quantity') }}</label>
                                <input class="form-control my-1" type="number" required name="quantity" @if (!empty($shortage)) value="{{ $shortage->quantity }}" @else
                                        value="{{ old('quantity') }}" @endif>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="type">{{ __('Type') }}</label>
                                    <select id="type" class="custom-select" name="type" required>
                                        <option value="min" @if((!empty($shortage)&&$shortage->type=='min')||(!empty($type)&&$type=='min'))selected @endif>{{ __('min') }}</option>
                                        <option value="plus" @if((!empty($shortage)&&$shortage->type=='plus')||(!empty($type)&&$type=='plus'))selected @endif>{{ __('plus') }}</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="state">{{ __('State') }}</label>
                                    <select id="state" class="custom-select" name="state" required>
                                        @if (!empty($shortage))
                                            <option value="{{ $shortage->state }}" selected>{{ __($shortage->state) }}
                                            </option>
                                        @endif
                                        <option value="waiting">{{ __('Waiting') }}</option>
                                        {{-- <option value="undeployed">{{__("undeployed")}}</option> --}}
                                        <option value="closed">{{ __('Closed') }}</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="details_ar">{{ __('Ar Details') }}:</label>

                                    <textarea class="form-control my-1" type="text"
                                        name="details_ar">@if (!empty($projReq)){{ $projReq->details_ar }} @else{{ old('details_ar') }} @endif</textarea>
                                </div>
                            </div>
                            <div class="col-md-6 ">
                                <div class="form-group">
                                    <label for="details_en">{{ __('EN Details') }}:</label>
                                    <textarea class="form-control my-1" type="text"
                                        name="details_en">@if (!empty($projReq)){{ $projReq->details_en }} @else{{ old('details_en') }} @endif</textarea>
                                </div>
                            </div>

                            <div class="col d-flex align-items-end d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shortages/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="card">
        <div class="card-header">
            <a id="top-plus" href="{{ route('shortages.create','min') }}" class="btn btn-outline-success btn-sm float-left">
                <i class="zmdi zmdi-plus"></i>
            </a>
        </div>
        <div class="card-body">

            <h5 class="card-title">{{ __('Manage Shortage') }}</h5>
            <div class="table-responsive border">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">{{ __('id') }}</th>
                            <th scope="col">{{ __('Charity') }}</th>
                            <th scope="col">{{ __('Quantity') }}</th>
                            <th scope="col">{{ __('Type') }}</th>
                            <th scope="col">{{ __('Item') }}</th>
                            <th scope="col">{{ __('Created at') }}</th>
                            <th scope="col">{{ __('State') }}</th>
                            <th scope="col" width="150">{{ __('Control') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($shortages as $shortage)
                            <tr>
                                <th scope="row">{{ $shortage->id }}</th>
                                <td>{{ $shortage->charity_id }}</td>
                                <td>{{ number_format($shortage->quantity) }}</td>
                                <td>{{ __($shortage->type) }}</td>
                                <td>
                                    @if (config('app.locale') == 'ar')
                                        {{ $shortage->item->name_ar }}
                                    @else
                                        {{ $shortage->item->name_en }}
                                    @endif
                                </td>
                                <td>{{ $shortage->created_at }}</td>
                                <td>{{ __($shortage->state) }}
                                    @if ($shortage->state != 'closed')
                                        <form action="{{ route('shortages.close', $shortage->id) }}" method="POST">
                                            @csrf
                                            @method('put')
                                            <button Type="submit" class="btn btn-outline-danger">
                                                {{ __('Close') }}
                                            </button>
                                        </form>
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-group-justified">
                                        <div class="btn-group">
                                            <a class="btn btn-outline-warning rounded-circle"
                                                href="{{ route('shortages.edit', $shortage->id) }}">
                                                <i class="zmdi zmdi-edit"></i>
                                            </a>
                                        </div>
                                        <div class="btn-group">
                                            <form action="{{ route('shortages.destroy', $shortage->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button Type="submit" class="btn rounded-circle btn-outline-danger">
                                                    <i class="zmdi zmdi-delete"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="btn-group-justified py-1">
                                        <div class="btn-group ">
                                            <a class="btn btn-outline-primary"
                                                href="{{ route('fills.index', $shortage->id) }}">
                                                {{ __('Fills Request') }}
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
@endsection

resources/views/shortages/surpIndex.blade.php
@extends('layouts.app')
@section('content')

    <div class="card">
        <div class="card-header">
            <a id="top-plus" href="{{ route('shortages.create','plus') }}" class="btn btn-outline-success btn-sm float-left">
                <i class="zmdi zmdi-plus"></i>
            </a>
        </div>
        <div class="card-body ">

            <h5 class="card-title">{{ __('Manage Surplus') }}</h5>
            <div class="table-responsive border">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">{{ __('id') }}</th>
                            <th scope="col">{{ __('Charity') }}</th>
                            <th scope="col">{{ __('Quantity') }}</th>
                            <th scope="col">{{ __('Type') }}</th>
                            <th scope="col">{{ __('Item') }}</th>
                            <th scope="col">{{ __('Created at') }}</th>
                            <th scope="col">{{ __('State') }}</th>
                            <th scope="col" width="150">{{ __('Control') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($surpluses as $sur)
                            <tr>
                                <th scope="row">{{ $sur->id }}</th>
                                <td>{{ $sur->charity_id }}</td>
                                <td>{{ number_format($sur->quantity) }}</td>
                                <td>{{ __($sur->type) }}</td>
                                <td>
                                    @if (config('app.locale') == 'ar')
                                        {{ $sur->item->name_ar }}
                                    @else
                                        {{ $sur->item->name_en }}
                                    @endif
                                </td>
                                <td>{{ $sur->created_at }}</td>
                                <td>{{ __($sur->state) }}
                                    @if ($sur->state != 'closed')
                                        <form action="{{ route('shortages.close', $sur->id) }}" method="POST">
                                            @csrf
                                            @method('put')
                                            <button Type="submit" class="btn btn-outline-danger">
                                                {{ __('Close') }}
                                            </button>
                                        </form>
                                    @endif
                                </td>
                                <td>

                                    <div class="btn-group-justified">

                                        <div class="btn-group">
                                            <a class="btn btn-outline-warning rounded-circle"
                                                href="{{ route('shortages.edit', $sur->id) }}">
                                                <i class="zmdi zmdi-edit"></i>
                                            </a>
                                        </div>
                                        <div class="btn-group">
                                            <form action="{{ route('shortages.destroy', $sur->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button Type="submit" class="btn rounded-circle btn-outline-danger">
                                                    <i class="zmdi zmdi-delete"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="btn-group-justified py-1">
                                        <div class="btn-group">
                                            <a class="btn btn-outline-primary"
                                                href="{{ route('fills.index', $sur->id) }}">
                                                {{ __('Fill') }}
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>


        </div>
    </div>
@endsection