routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// localization & switch language route
Route::get('locale/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'ar'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    App::setLocale($locale);
    return redirect()->back();
})->name('lang');

//Register & Login & Logout
Auth::routes();

// Route::get('/home', 'HomeController@base')->name('home');
Route::get('/reports','HomeController@index')->name('reports');


// public routes
//Primary Page
Route::get('/', 'HomeController@base')->name('base');
//About page
Route::view('/about', 'about.index')->name('about');

// -------------------------------------------------------------------------------------------------------

//Search Routes

Route::get('search/jobs', 'SearchController@jobs')->name('search.jobs'); //allJobs
Route::post('search/getjobs', 'SearchController@getJobs')->name('search.getJobs'); //search Jobs

Route::get('search/charities', 'SearchController@charities')->name('search.charities');
Route::post('search/charities', 'SearchController@getCharities')->name('search.getCharities'); //search Charities

Route::get('search/projects', 'SearchController@projects')->name('search.projects');
Route::post('search/projects', 'SearchController@getProjects')->name('search.getProjects'); //search Projects

Route::get('search/shortages', 'SearchController@shortages')->name('search.shortages');
Route::post('search/shortages', 'SearchController@getShortages')->name('search.getShortages'); //search Shortages

Route::get('search/surpluses', 'SearchController@surpluses')->name('search.surpluses');
Route::post('search/surpluses', 'SearchController@getSurpluses')->name('search.getSurpluses'); //search Surpluses

// Route::get('search/activities', 'SearchController@activities')->name('search.activities');
// Route::post('search/{activity}/activities', 'SearchController@getActivities')->name('search.getActivities'); //search Activities

// -------------------------------------------------------------------------------------------------------

// show Routes

//project show

Route::get('projects/{project}/show', 'ProjectController@show')->name('projects.show');
// Route::get('charities/{project}/requirments', 'ProjectRequirementController@show')->name('projReqs.show');

// -------------------------------------------------------------------------------------------------------

//Charity Show
Route::get('charities/{charity}/show', 'CharityController@show')->name('charities.show');
Route::get('charities/{charity}/projects', 'CharityController@projects')->name('charities.projects');
Route::get('charities/{charity}/shortages', 'CharityController@shortages')->name('charities.shortage');
Route::get('charities/{charity}/surpluses', 'CharityController@surpluses')->name('charities.surplus');
Route::get('charities/{charity}/jobs', 'CharityController@jobs')->name('charities.jobs');

// -------------------------------------------------------------------------------------------------------
Route::get('jobs/{job}/show', 'CharityJobController@show')->name('jobs.show');
// -------------------------------------------------------------------------------------------------------

// Auth pages
Route::middleware(['auth'])->group(function () {

    //item resource
    Route::resource('items', 'ItemController')->except(['show', 'create', 'edit']);

    //charity resource
    Route::resource('charities', 'CharityController')->except(['show']);

    //project resource
    Route::resource('projects', 'ProjectController')->except(['show']);
    Route::match(['put', 'post'], 'projects/{project}/close', 'ProjectController@close')->name('projects.close');

    //Project Requirment Routes
    Route::get('project/{project}/requirments', 'ProjectRequirementController@index')->name('projReqs.index');
    Route::get('project/{project}/requirments/create', 'ProjectRequirementController@create')->name('projReqs.create');

    Route::post('project/{project}/requirments', 'ProjectRequirementController@store')->name('projReqs.store');
    Route::get('project/requirments/{projReq}/edit', 'ProjectRequirementController@edit')->name('projReqs.edit');
    Route::match(['put', 'post'], 'project/requirments/{projReq}', 'ProjectRequirementController@update')->name('projReqs.update');
    Route::delete('project/requirments/{projReq}', 'ProjectRequirementController@destroy')->name('projReqs.destroy');
    Route::match(['put', 'post'], 'projReq/{projReq}/close', 'ProjectRequirementController@close')->name('projReqs.close');

    // //fill Project Requirment
    // Route::get('projReq/{projReq}/fills', 'FillProjReqController@index')->name('projReqs.fills.index');
    // Route::get('projReq/{projReq}/fills/create', 'FillProjReqController@create')->name('projReqs.fills.create');
    // Route::post('projReq/{projReq}/fills', 'FillProjReqController@store')->name('projReqs.fills.store');
    // Route::get('projReq/fills/{fill}/edit', 'FillProjReqController@edit')->name('projReqs.fills.edit');
    // Route::match(['put', 'post'], 'projReq/fill/fills/{fill}', 'FillProjReqController@update')->name('projReqs.fills.update');
    // Route::delete('projReq/fills/{fill}', 'FillProjReqController@destroy')->name('projReqs.fills.destroy');
    // Route::match(['put', 'post'], 'projReq/fills/{fill}/close', 'FillProjReqController@close')->name('projReqs.fills.close');

    //shortage resource
    Route::resource('shortages', 'ShortageController')->except('index', 'create');
    Route::get('shortages/type/{type}/index', 'ShortageController@index')->name('shortages.index');
    Route::get('shortages/type/{type}/create', 'ShortageController@create')->name('shortages.create');

    Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');

    //fill Shortage
    Route::get('shortage/{shortage?}/fills', 'FillController@index')->name('fills.index');
    Route::get('shortage/{shortage}/fills/create/', 'FillController@create')->name('fills.create');
    Route::post('shortage/{shortage}/fills', 'FillController@store')->name('fills.store');
    Route::get('shortage/fills/{fill}/edit', 'FillController@edit')->name('fills.edit');
    Route::match(['put', 'post'], 'shortage/fill/fills/{fill}', 'FillController@update')->name('fills.update');
    Route::delete('shortage/fills/{fill}', 'FillController@destroy')->name('fills.destroy');
    Route::match(['put', 'post'], 'shortage/fills/{fill}/close', 'FillController@close')->name('fills.close');



    //volunteer resource
    Route::resource('volunteers', 'VolunteerController');

    //jobs resource
    Route::resource('jobs', 'CharityJobController')->except(['show']);
    Route::match(['put', 'post'], 'jobs/{job}/close', 'CharityJobController@close')->name('jobs.close');

    //Job request Routes
    Route::get('jobreq/{job}/request', 'VolunteerRequestController@index')->name('jobReqs.index');
    Route::get('jobreq/{job}/request/create', 'VolunteerRequestController@create')->name('jobReqs.create');
    Route::post('jobreq/{job}/request', 'VolunteerRequestController@store')->name('jobReqs.store');
    Route::get('jobreq/request/{jobReq}/edit', 'VolunteerRequestController@edit')->name('jobReqs.edit');
    Route::match(['put', 'post'], 'jobreq/request/{jobReq}', 'VolunteerRequestController@update')->name('jobReqs.update');
    Route::delete('jobreq/request/{jobReq}', 'VolunteerRequestController@destroy')->name('jobReqs.destroy');

//benifactors && charity
    Route::get('user/fills', 'FillController@MyFills')->name('user.myFills');
    Route::get('user/jobReqs', 'VolunteerRequestController@myJobRequests')->name('user.jobReqs');
// Route::match(['put', 'post'], 'shortages/{shortage}/close', 'ShortageController@close')->name('shortages.close');
    // Route::resource('benfes', 'BenefactorController');


    //messages
Route::get('messages/index/{type}', 'MessageController@index')->name('messages.index');

// Route::get('fill/{fill}/messages', 'MessageController@index')->name('messages.fill.index');
Route::post('fill/{fill}/messages/type/{type}', 'MessageController@send')->name('messages.send');
Route::get('fill/{fill}/messages/type/{type}','MessageController@show')->name('fill.messages');
});

resources/views/articles/crup.blade.php
@extends('layouts.app')


@section('content')
<div class="row justify-content-center">
    <div class="col-md">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form action="{{empty($charity)? route('charities.store') : route('charities.update',$charity)}}"
                    method="Post" enctype="multipart/form-data">
                    @csrf
                    @if (!empty($charity))
                    @method('PUT')
                    @endif
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="name_ar">{{ __('Arabic Name') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="name_ar"
                                value=@if(!empty($charity))"{{$charity->name_ar}}"@else "{{old('name_ar')}}" @endif>
                        </div>
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="name_en">{{ __('English Name') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="name_en"
                                value=@if(!empty($charity))"{{$charity->name_en}}" @else "{{old('name_en')}}" @endif>
                        </div>
                    </div>
                    <!--cover-->
                    <div class="row">
                        <div class=" @if (!empty($charity)) col-md-2 @else col-md-4 @endif col-form-label ">
                            <label for="title">{{ __('Title') }}:</label>
                        </div>
                        @if (!empty($charity))
                        <div class="col-md-2 col-form-label">
                            <img src="{{ asset(config('path.covers').$charity->cover) }}"
                                class="img-fluid img-thumbnail">
                        </div>
                        @endif
                        <div class="col-8">
                            <input class="form-control" type="file" name="cover" @if (empty($charity)) required @endif>
                        </div>
                    </div>

                    <!--logo-->
                    <div class="row">
                        <div class=" @if (!empty($charity)) col-md-2 @else col-md-4 @endif col-form-label "
                            style="text-align:start">
                            <label for="logo">{{ __('Logo') }}:</label>
                        </div>
                        @if (!empty($charity))
                        <div class="col-md-2 col-form-label " style="text-align:start">
                            <img src="{{ asset(config('path.ch_logo').$charity->logo) }}"
                                class="img-fluid img-thumbnail">
                        </div>
                        @endif
                        <div class="col-8">
                            <input class="form-control" type="file" name="logo" @if (empty($charity)) required
                                @endif>
                        </div>
                    </div>

                    <!--name-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="name_ar">{{ __('Arabic Name') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="name_ar"
                                value=@if(!empty($charity))"{{$charity->name_ar}}"@else "{{old('name_ar')}}" @endif>
                        </div>
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="name_en">{{ __('English Name') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="name_en"
                                value=@if(!empty($charity))"{{$charity->name_en}}" @else "{{old('name_en')}}" @endif>
                        </div>
                    </div>


                    <!--license   ماخلصت-->
                    <!-- <div class="row">
                        {{-- <div class=" @if (!empty($charity)) col-md-2 @else col-md-4 @endif col-form-label " --}}
                            style="text-align:start">
                            {{-- <label for="license">{{ __('license') }}:</label> --}}
                        </div>
                        {{-- @if (!empty($charity)) --}}
                        <div class="col-md-2 col-form-label " style="text-align:start">
                            {{-- <img src="{{ asset('storage/charities/logo/' . $charity->license) }}" --}}
                                class="img-fluid img-thumbnail">
                        </div>
                        {{-- @endif --}}
                        <div class="col-8">
                            {{-- <input class="form-control" type="file" name="license" @if (empty($charity)) required --}}
                                {{-- @endif> --}}
                        </div>
                    </div> -->



                    <!--email-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="email">{{ __('Email') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="email"
                                value=@if(!empty($charity))"{{$charity->email}}" @else "{{old('email')}}" @endif>
                        </div>
                    </div>


                    <!--phone-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="phone">{{ __('Phone') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="phone"
                                value=@if(!empty($charity))"{{$charity->phone}}"@else "{{old('phone')}}" @endif>
                        </div>
                    </div>

                    <!--mobile-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="mobile">{{ __('Mobile') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="mobile"
                                value=@if(!empty($charity)) "{{$charity->mobile}}" @else "{{old('mobile')}}" @endif>
                        </div>
                    </div>


                    <!--whatsapp-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="whatsapp">{{ __('Whatsapp') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="whatsapp"
                                value=@if(!empty($charity)) "{{$charity->whatsapp}}" @else "{{old('whatsapp')}}" @endif>
                        </div>
                    </div>


                    <!--facebook-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="facebook">{{ __('Facebook') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="facebook"
                                value=@if(!empty($charity))"{{$charity->facebook}}" @else "{{old('facebook')}}" @endif>
                        </div>
                    </div>


                    <!-- address-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="address_ar">{{ __('Address_AR') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="address_ar"
                                value=@if(!empty($charity))"{{$charity->address_ar}}" @else "{{old('address_ar')}}"
                                @endif>
                        </div>
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="address_en">{{ __('Address_EN') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="address_en"
                                value=@if(!empty($charity) )"{{$charity->address_en}}" @else "{{old('address_en')}}"
                                @endif>
                        </div>
                    </div>


                    <!--info-->
                    <div class="row">
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="info_ar">{{ __('Info_AR') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="info_ar"
                                value=@if(!empty($charity)) "{{$charity->info_ar}}" @else "{{old('info_ar')}}" @endif>
                        </div>
                        <div class="col-md-2 col-form-label text-md-left">
                            <label for="info_en">{{ __('Info_EN') }}:</label>
                        </div>
                        <div class="col-4"><input class="form-control" type="text" name="info_en"
                                value=@if(!empty($charity)) "{{$charity->info_en}}" @else "{{old('info_en')}}" @endif>
                        </div>

                    </div>


                    <div class="row">
                        <div class="col-6 text-md-center">
                            <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                        </div>
                        <div class="col-6 text-md-center">
                            {{-- <a @can('admin') href="{{ route('charities.index') }}"@else href="{{ route('base') }}" @endcan type="button"
                                class="btn btn-secondary">{{ __('Cancel') }}</a> --}}
                                <a href="#" class="btn btn-secondary" onclick="location.href = document.referrer; return false;">{{ __('Cancel') }}</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')
@section('content')